module.exports = {
  roots: [ '<rootDir>/tests/' ],
  verbose: true,
  clearMocks: true,
  moduleFileExtensions: [ 'js' ],
  testEnvironment: 'node',
  testMatch: [ '**/*.test.js', '**/__tests__/**/?(*.)+(spec|test).js' ],
  testRunner: 'jest-circus/runner',
  testPathIgnorePatterns: [ '/node_modules/', '/__fixtures__/' ],
  collectCoverage: true,
  collectCoverageFrom: [
    '!**/dist/**',
    '!**/node_modules/**',
    '!**/vendor/**',
    '!**/generated/**',
    '!**/__fixtures__/**',
    '!**/scenarios/**',
    '!**/redirects/**',
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  coverageDirectory: './coverage',
  coverageReporters: [ 'json', 'lcov', 'text', 'clover', 'html' ],
};
